INSERT INTO public.mentors (email, display_name, campus, comunidad_id)
VALUES
  ('lpaez@tec.mx', 'Leonardo Páez Hervert', 'MTY', 'EKVILIBRO'),
  ('abril.de.leon@tec.mx', 'Abril Joana Margarita De León Rincón', 'MTY', 'EKVILIBRO'),
  ('mgflores@tec.mx', 'Martha Gabriela Flores Ramírez', 'MTY', 'EKVILIBRO'),
  ('carmenmora@tec.mx', 'María del Carmen Mora González', 'MTY', 'EKVILIBRO'),
  ('julianagt@tec.mx', 'Juliana Garza Treviño', 'MTY', 'EKVILIBRO'),
  ('mcristerna@tec.mx', 'Marco Vinicio Cristerna Mata', 'MTY', 'ENERGIO'),
  ('pame.mtz@tec.mx', 'Pamela Martínez Sepúlveda', 'MTY', 'ENERGIO'),
  ('ricardo.klein@tec.mx', 'Ricardo Acosta Klein', 'MTY', 'ENERGIO'),
  ('antonio.rivera@tec.mx', 'José Antonio Manuel Rodríguez Rivera', 'MTY', 'ENERGIO'),
  ('isabeldelagarza@tec.mx', 'Francisca Isabel De la Garza Núñez', 'MTY', 'ENERGIO'),
  ('zoe.montoya@tec.mx', 'Zoé Nohemí Montoya Campos', 'MTY', 'FORTA'),
  ('damaris.morales@tec.mx', 'Dámaris Yannaí Morales Leal', 'MTY', 'FORTA'),
  ('rowland@tec.mx', 'Antonio Rowland Ramos Díaz', 'MTY', 'FORTA'),
  ('atemoltzi@tec.mx', 'Arturo Temolzi Torres', 'MTY', 'FORTA'),
  ('egarzac@tec.mx', 'Enrique Adolfo Garza Chávez', 'MTY', 'FORTA'),
  ('jr.flores@tec.mx', 'José Ricardo Flores Espinoza', 'MTY', 'KREI'),
  ('kareng@tec.mx', 'Karen Ariadna Guzmán Vega', 'MTY', 'KREI'),
  ('kvillarreal@tec.mx', 'Karla Lorena Villarreal Aldape', 'MTY', 'KREI'),
  ('azuniga@tec.mx', 'Angélica Yolanda Zúñiga Montemayor', 'MTY', 'KREI'),
  ('jjfranklin@tec.mx', 'Juan José Franklin Uraga', 'MTY', 'KREI'),
  ('dacia.gzz@tec.mx', 'Dacia González Fernandez', 'MTY', 'KRESKO'),
  ('andrea.herrera@tec.mx', 'Andrea Herrera Morales', 'MTY', 'KRESKO'),
  ('pacelideluca@tec.mx', 'Gustavo Paceli de Luca Gallegos', 'MTY', 'KRESKO'),
  ('roger.rosado@tec.mx', 'Roger Rosado Montes', 'MTY', 'PASIO'),
  ('rodrigoehs@tec.mx', 'Rodrigo Eugenio Holguín Salinas', 'MTY', 'PASIO'),
  ('alma.mercado@tec.mx', 'Alma Beatriz Mercado Guerra', 'MTY', 'PASIO'),
  ('monserrat.tijerina@tec.mx', 'Monserrat Tijerina Cervantes', 'MTY', 'PASIO'),
  ('chantal.magallanes@tec.mx', 'Chantal Alejandra Magallanes Garza', 'MTY', 'REFLEKTO'),
  ('acorrea@tec.mx', 'Alinna Correa Escobedo', 'MTY', 'REFLEKTO'),
  ('lauramtz@tec.mx', 'Laura Lidia Martínez Ochoa', 'MTY', 'REFLEKTO'),
  ('ana.pinilla@tec.mx', 'Ana María Pinilla Torres', 'MTY', 'REFLEKTO'),
  ('abigailcepeda@tec.mx', 'Abigail Cepeda Hernández', 'MTY', 'REFLEKTO'),
  ('ernesto.rmz@tec.mx', 'Norman Ernesto Ramírez González', 'MTY', 'REVO'),
  ('rogelio.rivas@tec.mx', 'José Rogelio Rivas Pimentel', 'MTY', 'REVO'),
  ('fabby@tec.mx', 'Fabiola Guadalupe Villarreal García', 'MTY', 'REVO'),
  ('mmendiol@tec.mx', 'María del Roble Mendiola Delgado', 'MTY', 'REVO'),
  ('mogarcia@tec.mx', 'Montserrat García Yáñez', 'MTY', 'REVO'),
  ('dlcruz.jacob@tec.mx', 'Jacob de la Cruz Hinojosa', 'MTY', 'SPIRITA'),
  ('fabiolacamposs@tec.mx', 'Fabiola Ivette Campos Salgado', 'MTY', 'SPIRITA'),
  ('christopher.michaux@tec.mx', 'Christopher Jean-Philippe Josette Michaux', 'MTY', 'SPIRITA'),
  ('mauricionoriega@tec.mx', 'Jorge Mauricio Noriega Montemayor', 'MTY', 'TALENTA'),
  ('betyclub@tec.mx', 'Beatriz Eugenia González Canales', 'MTY', 'TALENTA'),
  ('brenda.r@tec.mx', 'Brenda Alicia Ramírez Téllez', 'MTY', 'TALENTA'),
  ('lgrc@tec.mx', 'Laura Gabriela Ríos Contreras', 'MTY', 'TALENTA'),
  ('sami.suro@tec.mx', 'Samira Susana Suro Barbosa', 'MTY', 'TALENTA')
ON CONFLICT (email) DO UPDATE SET display_name = EXCLUDED.display_name, campus = EXCLUDED.campus, comunidad_id = EXCLUDED.comunidad_id;
