-- Seed de mentores con datos de contacto (WhatsApp e Instagram) desde DATOSME_CURSOR.csv
-- Nota: Ejecutar migración 0008_add_mentor_contact.sql primero

INSERT INTO public.mentors (email, display_name, campus, comunidad_id, whatsapp, instagram)
VALUES
  ('lpaez@tec.mx', 'Leonardo Páez Hervert', 'MTY', 'EKVILIBRO', '8126200568', 'ekvilibromty'),
  ('abril.de.leon@tec.mx', 'Abril Joana Margarita De León Rincón', 'MTY', 'EKVILIBRO', '8113013930', 'ekvilibromty'),
  ('mgflores@tec.mx', 'Martha Gabriela Flores Ramírez', 'MTY', 'EKVILIBRO', '8116316438', 'ekvilibromty'),
  ('carmenmora@tec.mx', 'María del Carmen Mora González', 'MTY', 'EKVILIBRO', '8123191472', 'ekvilibromty'),
  ('julianagt@tec.mx', 'Juliana Garza Treviño', 'MTY', 'EKVILIBRO', '8183665654', 'ekvilibromty'),
  ('mcristerna@tec.mx', 'Marco Vinicio Cristerna Mata', 'MTY', 'ENERGIO', '8117905183', 'energiomty'),
  ('pame.mtz@tec.mx', 'Pamela Martínez Sepúlveda', 'MTY', 'ENERGIO', '8126200565', 'energiomty'),
  ('ricardo.klein@tec.mx', 'Ricardo Acosta Klein', 'MTY', 'ENERGIO', '8116820747', 'energiomty'),
  ('antonio.rivera@tec.mx', 'José Antonio Manuel Rodríguez Rivera', 'MTY', 'ENERGIO', '8119996494', 'energiomty'),
  ('isabeldelagarza@tec.mx', 'Francisca Isabel De la Garza Núñez', 'MTY', 'ENERGIO', '8183665657', 'energiomty'),
  ('zoe.montoya@tec.mx', 'Zoé Nohemí Montoya Campos', 'MTY', 'FORTA', '8116824512', 'forta_mty'),
  ('damaris.morales@tec.mx', 'Dámaris Yannaí Morales Leal', 'MTY', 'FORTA', '8183665655', 'forta_mty'),
  ('rowland@tec.mx', 'Antonio Rowland Ramos Díaz', 'MTY', 'FORTA', '8120223400', 'forta_mty'),
  ('atemoltzi@tec.mx', 'Arturo Temolzi Torres', 'MTY', 'FORTA', '8118249660', 'forta_mty'),
  ('egarzac@tec.mx', 'Enrique Adolfo Garza Chávez', 'MTY', 'FORTA', '8183665653', 'forta_mty'),
  ('jr.flores@tec.mx', 'José Ricardo Flores Espinoza', 'MTY', 'KREI', '8126200576', 'kreimty'),
  ('kareng@tec.mx', 'Karen Ariadna Guzmán Vega', 'MTY', 'KREI', '8128612913', 'kreimty'),
  ('kvillarreal@tec.mx', 'Karla Lorena Villarreal Aldape', 'MTY', 'KREI', '8123503535', 'kreimty'),
  ('azuniga@tec.mx', 'Angélica Yolanda Zúñiga Montemayor', 'MTY', 'KREI', '8110405285', 'kreimty'),
  ('jjfranklin@tec.mx', 'Juan José Franklin Uraga', 'MTY', 'KREI', '7712957845', 'krei.mty'),
  ('dacia.gzz@tec.mx', 'Dacia González Fernandez', 'MTY', 'KRESKO', '8182596514', 'kresko.mty'),
  ('andrea.herrera@tec.mx', 'Andrea Herrera Morales', 'MTY', 'KRESKO', '8126200567', 'kresko.mty'),
  ('pacelideluca@tec.mx', 'Gustavo Paceli de Luca Gallegos', 'MTY', 'KRESKO', '8112816230', 'kresko.mty'),
  ('aleyda.fernandez@tec.mx', 'Aleyda Carime Fernández Marchán', 'MTY', 'KRESKO', '4921436212', 'kresko.mty'),
  ('roger.rosado@tec.mx', 'Roger Rosado Montes', 'MTY', 'PASIO', '8110443634', 'pasiomty'),
  ('rodrigoehs@tec.mx', 'Rodrigo Eugenio Holguín Salinas', 'MTY', 'PASIO', '8126200564', 'pasiomty'),
  ('alma.mercado@tec.mx', 'Alma Beatriz Mercado Guerra', 'MTY', 'PASIO', '8116837240', 'pasiomty'),
  ('monserrat.tijerina@tec.mx', 'Monserrat Tijerina Cervantes', 'MTY', 'PASIO', '8183665649', 'pasiomty'),
  ('chantal.magallanes@tec.mx', 'Chantal Alejandra Magallanes Garza', 'MTY', 'REFLEKTO', '8441069980', 'reflekto.mty'),
  ('acorrea@tec.mx', 'Alinna Correa Escobedo', 'MTY', 'REFLEKTO', '8117907922', 'reflekto.mty'),
  ('lauramtz@tec.mx', 'Laura Lidia Martínez Ochoa', 'MTY', 'REFLEKTO', '8126220161', 'reflekto.mty'),
  ('ana.pinilla@tec.mx', 'Ana María Pinilla Torres', 'MTY', 'REFLEKTO', '8182031461', 'reflekto.mty'),
  ('abigailcepeda@tec.mx', 'Abigail Cepeda Hernández', 'MTY', 'REFLEKTO', '8120109380', 'reflekto.mty'),
  ('ernesto.rmz@tec.mx', 'Norman Ernesto Ramírez González', 'MTY', 'REVO', '8116214374', 'revo.mty'),
  ('rogelio.rivas@tec.mx', 'José Rogelio Rivas Pimentel', 'MTY', 'REVO', '8126200569', 'revo.mty'),
  ('fabby@tec.mx', 'Fabiola Guadalupe Villarreal García', 'MTY', 'REVO', '8120405897', 'revo.mty'),
  ('mmendiol@tec.mx', 'María del Roble Mendiola Delgado', 'MTY', 'REVO', '8134030709', 'revo.mty'),
  ('mogarcia@tec.mx', 'Montserrat García Yáñez', 'MTY', 'REVO', '8134047958', 'revo.mty'),
  ('dlcruz.jacob@tec.mx', 'Jacob de la Cruz Hinojosa', 'MTY', 'SPIRITA', '8115316938', 'spiritamty'),
  ('fabiolacamposs@tec.mx', 'Fabiola Ivette Campos Salgado', 'MTY', 'SPIRITA', '8180996388', 'spiritamty'),
  ('christopher.michaux@tec.mx', 'Christopher Jean-Philippe Josette Michaux', 'MTY', 'SPIRITA', '8120109389', 'spiritamty'),
  ('mauricionoriega@tec.mx', 'Jorge Mauricio Noriega Montemayor', 'MTY', 'TALENTA', '8115314270', 'talenta.mty'),
  ('betyclub@tec.mx', 'Beatriz Eugenia González Canales', 'MTY', 'TALENTA', '8115316186', 'talenta.mty'),
  ('brenda.r@tec.mx', 'Brenda Alicia Ramírez Téllez', 'MTY', 'TALENTA', '8126200579', 'talenta.mty'),
  ('lgrc@tec.mx', 'Laura Gabriela Ríos Contreras', 'MTY', 'TALENTA', '8115866286', 'talenta.mty'),
  ('sami.suro@tec.mx', 'Samira Susana Suro Barbosa', 'MTY', 'TALENTA', '8134030715', 'talenta.mty')
ON CONFLICT (email) DO UPDATE SET 
  display_name = EXCLUDED.display_name, 
  campus = EXCLUDED.campus, 
  comunidad_id = EXCLUDED.comunidad_id,
  whatsapp = EXCLUDED.whatsapp,
  instagram = EXCLUDED.instagram;

